model_params:
  model_name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128


data_params:
  dataset_name: celeba 
  data_dir: "D:/aigc/dataset"
  train_batch_size: 512
  val_batch_size:  64
  patch_size: 64
  num_workers: 0


exp_params:
  exp_name: "exp2"
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  device: 0
  max_epochs: 100
  checkpoint_dir: "./checkpoint2"
  log_dir: "logs/"
  
